# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate Images and Update README

on:
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
 contents: read
jobs:
  build:
    if: github.event.pull_request.merged == true && github.head_ref != 'docs/generate_readme'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Test with pytest
      run: |
        pytest
  generate:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Generate icons
      run: python src/main.py

    - name: Generate README
      run: python src/generate_readme.py
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./output
  documentation:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
        git checkout main
        git checkout -b docs/generate_readme
        git add docs/index.md
        git commit -m 'docs: update index.md' || exit 0
        git push --set-upstream origin docs/generate_readme

    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: output/*
